name: Test Merge Commit
on: pull_request

permissions:
  contents: read

jobs:
  test-merge:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          # arch isn't used and we have no way to use it currently
          - { os: macos-latest, arch: x64 }
          - { os: ubuntu-latest, arch: x64 }
          - { os: windows-latest, arch: x64 }
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # v2
      - uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
      - uses: codecov/codecov-action@2a829b95deaeea2d11d127cc0358005714ff35ea # v2
        with:
          directory: ./coverage/
